### ISSUE TITLE
Local video track created but unable to view it on the video view

### ISSUE THREAD

**Issue by maneeshsakthi** [twilio/video-quickstart-objc#108]
### Description

Using TVILocalVideoTrack's trackWithCapturer method to create the local video and the LocalVideoTrack it is not null , but when i add a renderer to this track i am unable to see the video on the twilio video view, 

#### Code

```objc
TVIVideoView *myVideo =  [[TVIVideoView alloc]initWithFrame:CGRectMake(0, 0, 200, 200)];
    myVideo.opaque = YES;
    myVideo.clearsContextBeforeDrawing = YES;
    myVideo.autoresizesSubviews = YES;
    myVideo.alpha = 1;
    myVideo.backgroundColor = UIColor.darkGrayColor;
    
    TVILocalVideoTrack *localVideoTrack;
    TVICameraCapturer *camera =  [[TVICameraCapturer alloc] initWithSource:TVICameraCaptureSourceFrontCamera delegate:self];
    
    localVideoTrack = [TVILocalVideoTrack trackWithCapturer:camera
                                                         enabled:YES
                                                     constraints:nil
                                                            name:@"Camera"];

 if (!localVideoTrack) {
        printf("Failed to load Video track");
    } else {
        NSLog(localVideoTrack.trackId);
        [localVideoTrack addRenderer:myVideo];
       // myVideo.mirror = (camera.source == TVICameraCaptureSourceFrontCamera);
        localVideoTrack.enabled = YES;
    
    }

```

#### Expected Behavior

Video to be shown

#### Actual Behavior

no video being shown 

#### Reproduces How Often

100%

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

 pod 'TwilioVideo', '2.0.0-beta3'

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by paynerc** [comment]
Quick question are you adding the `TVIVideoView` into your displayed view hierarchy anywhere? 

If you are creating a `TVIVideoView` programmatically, you will need to add it to your view hierarchy for it to be displayed. For instance, take a look at the code in [`setupRemoteView`](https://github.com/twilio/video-quickstart-objc/blob/master/ObjCVideoQuickstart/ViewController.m#L202-L208). We allocate the `TVIVideoView`, perform some configuration and then call `insertSubview:atIndex:` on the view controller's view so that it will be displayed.

Let me know if that doesn't solve your issue.

Thanks!

Ryan

**Comment by maneeshsakthi** [comment]
Hey thanks a lot for the quick reply , and yes i have added the view on to the view hierarchy i have even set a background color to the TVIVideoView to know if its there and visible , and yes i am able to see the TVIVideoView but not the local video track.

**Comment by paynerc** [comment]
Hrm. That is strange. From your code it didn't appear that the view was being added to the hierarchy. Would you be able to post a running example that reproduces this issue? I have not been able to reproduce it myself.

**Comment by ijasnahamed** [comment]
I am integrating video to my static library. I have my preview view in my xib view file not programatically creating. When i render my local video track, its not showing in my view.

When I further checked on code, I get no camera sources but my phones have both front and back.

**Comment by ceaglest** [comment]
Hi @ijasnahamed,

If you're still having issues building a static library which depends on TwilioVideo.framework then you might want to try out our static library artifacts. We have been releasing both a dynamic framework and a static library since version [2.5.2](
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#252-october-8-2018).

> [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo].count;

This particular issue has been reported when integrating with Adobe Air and using TwilioVideo.framework. It shouldn't occur with the static lib.

Let us know if this helps,
Chris

**Comment by paynerc** [comment]
@rickyrobinett,

Just checking in to see if you had any success with the static library that we are now shipping. 

Thanks,

Ryan

**Comment by paynerc** [comment]
@rickyrobinett,

At this point I am assuming that you have gotten past the issue you were experiencing. Feel free to reach out if you are still having issues.

Thanks,

Ryan
