### ISSUE TITLE
Sounds from surrounded environment interfere with the conversation.

### ISSUE THREAD

**Issue by Base2526** [twilio/video-quickstart-objc#119]
Hi. all friend
When making voice call, I heard echo of my own voice when speaking, how do I get rid of that echo and noise and make the quality of human voice better.

pod 'TwilioVideo', '~> 2.2.0'
Thx.

**Comment by piyushtank** [comment]
@Base2526 Thanks for reaching out.  The video SDK uses the iPhone's in-built echo cancellation. In order to debug the problem can you provide following information -
1. The device and iOS version where you are observing the echo problem.
2. Are you able to reproduce the problem on our Quickstart sample app?
