### ISSUE TITLE
Integrating Google Speech API with Twilio Conversation? 

### ISSUE THREAD

**Issue by vikram-gupta** [twilio/video-quickstart-objc#27]
Hi Team,

I tried to integrate the Google Speech API (streaming) with the Twilio Conversation sample app (Objective-C) so that i can do speech recognition along with video chat. Here is the [link](https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/speech/Objective-C/Speech-gRPC-Streaming) to the Google Speech API sample app that I am integrated.

But I keep getting a continuous and weird clicking noise in place of the actual audio. The video just works fine. My suspicion is that both the Twilio API and Google API use the AVAudioSession and in some way they are interacting in an unwanted way.

Any pointers or suggestions?

**Comment by ptankTwilio** [comment]
Hi Vikram,

Thanks for using the Video SDK and reaching out to us.

For Video Conversations SDK version v0.25.1, can you try setting audioOutputMode to `TWCAudioOutputApplication` on `TwilioConversationsClient` object ? 

Also we have released Rooms based [Video SDK Version 1.0.0-Beta](https://media.twiliocdn.com/sdk/ios/video/releases/1.0.0-beta1/twilio-video-ios-1.0.0-beta1.tar.bz2). In new Rooms based Video SDK, we are planning to provide APIs to control audio (e.g. sampling rates and audio samples) in your app. The new sdk will be available soon for developers to use.

Please let me know if this helps.

Thank you,
Piyush Tank

**Comment by ceaglest** [comment]
@vikram-gupta I would definitely recommend giving our new betas a try as @ptankTwilio suggested. However, there is currently no way to get sample level access to the raw audio stream being captured by our SDK. I believe this is what you will need in order to stream data to Google's speech APIs.

Thanks for the feedback, and we will certainly consider adding this feature during the beta process.

Cheers,
Chris
