### ISSUE TITLE
Getting zero participants in the Room passed to didConnectToRoom

### ISSUE THREAD

**Issue by alexiss03** [twilio/video-quickstart-objc#52]
Hi! I am getting zero participants when I get the room.participants.count in the room passed to didConnectToRoom method. Is this the intended behavior? If yes, does this mean that the participant that recently connected to the room is not included in the room that is passed to didConnectToRoom? Thanks.

**Comment by ceaglest** [comment]
Hi @alexiss03,

At the time `didConnectToRoom:` is called you should be able to query the `TVIRoom` instance and get the current list of Participants.

If Client `Alice` joins a Room where `Bob` is already present then `room.participants.count == 1`. Is there a case where you don't see this behavior? We have pretty extensive tests that validate this condition, but please let us know if you are seeing otherwise.

Best,
Chris Eagleston

**Comment by alexiss03** [comment]
I am experiencing the behavior you discussed. But by the time Alice joined a Room, is she still not included in the participants contained in that Room? In your example, does room.participants.count == 2 you should be the case because Alice has already joined that Room? I am pertaining to the Room given by didConnectToRoom.

Thanks,
Lexi

**Comment by ceaglest** [comment]
Hi @alexiss03,

Your own Participant `Alice` is not included in `participants`. Please see the `localParticipant` property, which is set once you've connected to a Room.

Cheers,
Chris

**Comment by alexiss03** [comment]
Ah, I see. Thanks a lot.

Cheers,
Lexi

**Comment by ceaglest** [comment]
Hi @alexiss03,

No problem, and sorry for misreading your original question. I'll close this one out as answered.

Cheers,
Chris
