### ISSUE TITLE
Release for GA

### ISSUE THREAD

**Issue by alexiss03** [twilio/video-quickstart-objc#55]
Hi! Our app submission is currently being constantly rejected by the App Store unless we resolve the issue they raised by migrating to Twilio Video. Can we know when is the GA release of Twilio Video so we can manage our expectations? 

Thanks,
Lexi

**Comment by ptankTwilio** [comment]
Hi Lexi,

This is definitely concerning and, we would like to fix it as soon as possible if there is any problem. Can you provide more details why Twilio Video is causing the App Store rejection?  Also, please note that we have not received such complaints from other complaints. 

I will talk to the team and get back to you with the GA timeframe soon.

Thanks,
Piyush

**Comment by alexiss03** [comment]
Hi Piyush, sorry for the confusion. We experienced the App Store rejection because the build we tried to submit is still using the TwilioConversationsClient framework. We haven't tried to submit the build with the implemented Twilio Video because we are still waiting for its GA. Our team will be waiting for the GA timeframe so that we can re-submit to the App Store soon.


Thanks,
Lexi

**Comment by ptankTwilio** [comment]
Hi Lexi,

We are planning to do GA release of Twilio Video in mid-April.  

Since Twilio Video is very close to GA, we recommend migrating to Twilio Video from TwilioConversationsClient. Here are the links to TwilioVideo Changelogs  and Downloads - [ChangeLogs](https://www.twilio.com/docs/api/video/changelogs/ios#100-beta10-march-10-2017), [Download](https://www.twilio.com/docs/api/video/download-video-sdks#ios-sdk)

Please let me know if you have more questions.

Thanks,
Piyush

**Comment by ptankTwilio** [comment]
Hi Lexi, 

Can you share the details why App Store rejected the app using TwilioConversationsClient ? 

We are concerned because, in Twilio Video, we are re-using good amount of code we used in TwilioConvesationsClient. So would like to confirm that Twilio Video would not cause any future App Store rejection.

Thank you!

Piyush

**Comment by alexiss03** [comment]
Hi Piyush,


According to Apple, upon launch, our app crashes when connected to IPv6. If it does any help on your side, attached here is the symbolicated log of the said crash. I hope this helps. 
[IPv6-crash-log.txt](https://github.com/twilio/video-quickstart-objc/files/860432/IPv6-crash-log.txt)


Thanks,
Lexi

**Comment by ptankTwilio** [comment]
@alexiss03 We have fixed the crash in our Room based TwilioVideo SDK. See [here](https://github.com/twilio/video-quickstart-swift/issues/92) for details.

**Comment by alexiss03** [comment]
Hi Piyush,

This is good to hear. Thanks for the update!

Thanks,
Lexi

**Comment by ceaglest** [comment]
Hi @alexiss03,

We are now live with our 1.0.0 GA release, please give it a try when you get the chance. As @ptankTwilio mentioned we've fixed the crash / app store rejection issue that you were experiencing with the older Conversations SDK during the 1.0 beta period.

https://www.twilio.com/docs/api/video/changelogs/ios#100-april-26-2017

Best,
Chris

**Comment by alexiss03** [comment]
Hi Chris,

We've already submitted our app that used one of your Twilio Video betas to the App Store. It was approved on Apple's end. Still, thank you for the update.

Cheers,
Lexi

**Comment by ceaglest** [comment]
Hi Lexi,

Excellent news! I'm going to close out this ticket now that you've been able to submit to Apple, and our GA is available.

Best,
Chris
