### ISSUE TITLE
Very poor video performance on A5 device

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-objc#87]
### Description

We are seeing very poor video performance on ipad Mini1s (A1454).  (stuttering, dropped connections, no audio etc).  We have eliminated the network connection as the source of problems since an iphone6 works really well from the same location.

Our best guess is that it is related to VP8 being in SW:
https://github.com/twilio/video-quickstart-swift/issues/88

We want to switch to 2.0 and H.264, but wanted to know if we are barking up the wrong tree.  Have you done any testing on low end iOS devices.  Is this problem because of the A5 chip (much slower than an A6) or the screensize of the ipad, etc?

### Steps to Reproduce

1. One end of the connection 

#### Code

We are using react-native with our own custom built wrapper. BTW, we would love to give it to Twilio to maintain and improve.

#### Expected Behavior

Acceptable video connections and no drops.

#### Actual Behavior

Poor quality video, laggy, and unreliable.

#### Reproduces How Often

100%

#### Logs

No logs.

### Versions

None

#### Video iOS SDK

1.1.0 via CocoaPods

#### Xcode

9.0

#### iOS Version

10.3.3

#### iOS Device

Original iPad Mini

**Comment by mcorner** [comment]
Also, we are using group rooms with only two participants.  Does p2p have less or more CPU load?

**Comment by ceaglest** [comment]
Hi @mcorner,

We don't officially support A5 based devices like the original iPad Mini. That being said, p2p Rooms will be slightly more efficient than Group Rooms when using `TVICameraCapturer` since physical rotations are not needed.

https://www.twilio.com/docs/api/video/download-video-sdks#supported-devices_1

Our latest 1.x releases (1.3.6 at the moment) improve performance on 64-bit devices by offering zero-copy Metal rendering. If you pickup our 2.0.0-preview4 release you can use H.264 which may offer better performance on older 32-bit devices. Because we don't officially support the A5 I haven't personally tried H.264 on these devices.

Regards,
Chris Eagleston

**Comment by mcorner** [comment]
Got it, exactly the information we are looking for.  We will try 2.0 and see what that does.  If it is still poor we may have to tell users they can't use our video features on those devices.  

And our offer on ReactNative is serious.  I would much rather you did all the work of maintaining it :)
